const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Plugins.Mouse,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Стеження: 0},
	{ОбмеженняРівнем: 0},
	{РобоКотик: 0},
	{Solid: 0},
	{ТраваПлатформа: 0},
	{Лава: 0},
	{Монетка: 0},
	{Якір: 0},
	{ТекстМонети: 0},
	{Колючка: 0},
	{ЗаднійФон: 0},
	{МапаТайлів: 0},
	{Спрайт: 0},
	{ТвердеТіло: 0},
	{ПІДЛОГА: 0},
	{Спрайт2: 0},
	{Миша: 0},
	{ЗнищенняПозаРівнем: 0},
	{Куля: 0},
	{Пуля: 0},
	{Дотик: 0},
	{ArrowUp: 0},
	{ArrowRight: 0},
	{ArrowLeft: 0},
	{money: 0}
];

self.InstanceType = {
	РобоКотик: class extends self.ISpriteInstance {},
	ТраваПлатформа: class extends self.ISpriteInstance {},
	Лава: class extends self.ISpriteInstance {},
	Монетка: class extends self.ISpriteInstance {},
	ТекстМонети: class extends self.ITextInstance {},
	Колючка: class extends self.ISpriteInstance {},
	ЗаднійФон: class extends self.ITiledBackgroundInstance {},
	МапаТайлів: class extends self.ITilemapInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ПІДЛОГА: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Миша: class extends self.IInstance {},
	Пуля: class extends self.ISpriteInstance {},
	Дотик: class extends self.IInstance {},
	ArrowUp: class extends self.ISpriteInstance {},
	ArrowRight: class extends self.ISpriteInstance {},
	ArrowLeft: class extends self.ISpriteInstance {}
}